topologies:
  build: &build
    name: build
    cpu: 2
    memory: 3800
  master_1repl: &master_1repl
    name: master_1repl
    cpu: 4
    memory: 6750
  master_1repl_1client: &master_1repl_1client
    name: master_1repl_1client
    cpu: 4
    memory: 8000
  ipaserver: &ipaserver
    name: ipaserver
    cpu: 2
    memory: 2750
  master_2repl_1client: &master_2repl_1client
    name: master_2repl_1client
    cpu: 5
    memory: 10750
  master_3repl_1client: &master_3repl_1client
    name: master_3repl_1client
    cpu: 6
    memory: 13500
  ad_master_1repl_1client: &ad_master_1repl_1client
    name: ad_master_1repl_1client
    cpu: 6
    memory: 12096

jobs:
  389ds-fedora/build:
    requires: []
    priority: 100
    job:
      class: Build
      args:
        copr: 'jamiechap/389-ds-pr-validation'
        git_repo: '{git_repo}'
        git_refspec: '{git_refspec}'
        template: &ci-master-latest
          name: freeipa/ci-master-f41
          version: 0.0.1
        timeout: 1800
        topology: *build

  389ds-fedora/automember:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        copr: 'jamiechap/389-ds-pr-validation'
        test_suite: test_integration/test_automember.py
        template: *ci-master-latest
        timeout: 6300
        topology: *master_1repl

  389ds-fedora/ipahealthcheck:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunPytest
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        copr: 'jamiechap/389-ds-pr-validation'
        test_suite: test_integration/test_ipahealthcheck.py::TestIpaHealthCheck
        template: *ci-master-latest
        timeout: 6300
        topology: *master_1repl_1client

  389ds-fedora/webui_identity:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        copr: 'jamiechap/389-ds-pr-validation'
        test_suite: >-
          test_webui/test_automember.py
          test_webui/test_idviews.py
        template: *ci-master-latest
        timeout: 4200
        topology: *ipaserver

  389ds-fedora/webui_general:
    requires: [389ds-fedora/build]
    priority: 50
    job:
      class: RunWebuiTests
      args:
        build_url: '{389ds-fedora/build_url}'
        update_packages: True
        copr: 'jamiechap/389-ds-pr-validation'
        test_suite: >-
          test_webui/test_loginscreen.py
          test_webui/test_misc_cases.py
          test_webui/test_navigation.py
          test_webui/test_translation.py
        template: *ci-master-latest
        timeout: 3600
        topology: *ipaserver

